[package]
name = "jackpot_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jackpot_program"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
jackpot_program = { path = "../jackpot_program" }

[profile.release]
overflow-checks = true
